-- OWB Agentic Gaming Dashboard - Query 10: MRR Proxy (Monthly Recurring Revenue)
-- Estimates monthly recurring revenue from:
--   1. Staking fees (penalty-based revenue from early unstaking)
--   2. Game shop revenue (OWB spent in-game, tracked via token burns/transfers)
--   3. DEX trading fees generated by OWB liquidity pools
-- Save as: "OWB Gaming - MRR Proxy"

WITH monthly_staking AS (
    SELECT
        DATE_TRUNC('month', t.block_time) AS month,
        COUNT(*) AS staking_txs,
        COUNT(DISTINCT t."from") AS staking_users,
        -- Estimate gas spent on staking (proxy for engagement)
        SUM(t.gas_used * t.gas_price / 1e18) AS staking_eth_gas
    FROM base.transactions t
    WHERE t."to" = 0x98430ECBe49bf6dB549D6F827d95ed7A3625FAeb
      AND t.block_time >= DATE '2025-06-01'
      AND t.success = true
    GROUP BY 1
),

monthly_claims AS (
    SELECT
        DATE_TRUNC('month', t.block_time) AS month,
        COUNT(*) AS claim_txs,
        COUNT(DISTINCT t."from") AS claim_users,
        SUM(t.gas_used * t.gas_price / 1e18) AS claims_eth_gas
    FROM base.transactions t
    WHERE t."to" = 0x0fbBBd928EA4eDDd2EAfF51D4D412a3b65452F40
      AND t.block_time >= DATE '2025-06-01'
      AND t.success = true
    GROUP BY 1
),

monthly_dex AS (
    SELECT
        DATE_TRUNC('month', block_time) AS month,
        SUM(amount_usd) AS total_volume_usd,
        COUNT(*) AS trade_count,
        COUNT(DISTINCT tx_from) AS unique_traders,
        -- Estimate trading fee revenue (weighted avg across fee tiers)
        -- Uniswap V3 0.01% + Aerodrome ~0.3% + Uniswap V4 0.3%
        SUM(amount_usd) * 0.002 AS est_lp_fee_revenue
    FROM dex.trades
    WHERE blockchain = 'base'
      AND (
          token_bought_address = 0xEF5997c2cf2f6c138196f8a6203afc335206b3c1
          OR token_sold_address = 0xEF5997c2cf2f6c138196f8a6203afc335206b3c1
      )
      AND block_time >= DATE '2025-06-01'
    GROUP BY 1
),

-- OWB token transfers to known ecosystem addresses (game shop proxy)
-- Track OWB flowing to non-pool, non-staking addresses (potential game revenue)
monthly_token_activity AS (
    SELECT
        DATE_TRUNC('month', block_time) AS month,
        COUNT(*) AS transfer_count,
        SUM(amount) AS total_owb_transferred,
        COUNT(DISTINCT "from") AS unique_senders
    FROM tokens.transfers
    WHERE blockchain = 'base'
      AND contract_address = 0xEF5997c2cf2f6c138196f8a6203afc335206b3c1
      AND block_date >= DATE '2025-06-01'
      AND "to" NOT IN (
          0xf252f51919dfca2c9c0ea279f11183580edee4d6,  -- Uniswap V3 pool
          0x995985C9027E8a90C823a5E0a9112Fea72d1F4DD,  -- Aerodrome pool
          0x98430ECBe49bf6dB549D6F827d95ed7A3625FAeb,  -- Staking
          0x0000000000000000000000000000000000000000   -- Null address
      )
    GROUP BY 1
)

SELECT
    COALESCE(ms.month, mc.month, md.month, mt.month) AS "Month",
    -- Staking metrics
    COALESCE(ms.staking_txs, 0) AS "Staking Txs",
    COALESCE(ms.staking_users, 0) AS "Unique Stakers",
    -- Claims metrics
    COALESCE(mc.claim_txs, 0) AS "Claim Txs",
    COALESCE(mc.claim_users, 0) AS "Unique Claimers",
    -- DEX metrics
    ROUND(COALESCE(md.total_volume_usd, 0), 2) AS "DEX Volume (USD)",
    COALESCE(md.trade_count, 0) AS "DEX Trades",
    COALESCE(md.unique_traders, 0) AS "DEX Traders",
    ROUND(COALESCE(md.est_lp_fee_revenue, 0), 2) AS "Est LP Fee Revenue (USD)",
    -- Token activity
    COALESCE(mt.transfer_count, 0) AS "Token Transfers",
    ROUND(COALESCE(mt.total_owb_transferred, 0), 0) AS "OWB Transferred",
    COALESCE(mt.unique_senders, 0) AS "Unique Token Senders",
    -- Composite MRR proxy
    ROUND(
        COALESCE(md.est_lp_fee_revenue, 0)
        + (COALESCE(ms.staking_eth_gas, 0) + COALESCE(mc.claims_eth_gas, 0)) * 2000  -- ETH price approximation
    , 2) AS "Est Total Monthly Revenue (USD)",
    -- MoM growth
    ROUND(
        100.0 * (
            COALESCE(ms.staking_txs, 0) + COALESCE(mc.claim_txs, 0) + COALESCE(md.trade_count, 0)
        ) / NULLIF(
            LAG(COALESCE(ms.staking_txs, 0) + COALESCE(mc.claim_txs, 0) + COALESCE(md.trade_count, 0))
            OVER (ORDER BY COALESCE(ms.month, mc.month, md.month, mt.month)),
            0
        ) - 100,
        1
    ) AS "MoM Activity Growth %"
FROM monthly_staking ms
FULL OUTER JOIN monthly_claims mc ON ms.month = mc.month
FULL OUTER JOIN monthly_dex md ON COALESCE(ms.month, mc.month) = md.month
FULL OUTER JOIN monthly_token_activity mt ON COALESCE(ms.month, mc.month, md.month) = mt.month
ORDER BY 1
